//
//  UIColor+ZeplinAdditions.swift
//
//  Generated by Zeplin on 9/22/16.
//  Copyright (c) 2016 Five Agency. All rights reserved. 
//

import UIKit

extension UIColor {
	class func highlightRedColor() -> UIColor {
		return UIColor(red: 218.0 / 255.0, green: 50.0 / 255.0, blue: 40.0 / 255.0, alpha: 1.0)
	}

	class func headerLightGrayColor() -> UIColor {
		return UIColor(white: 237.0 / 255.0, alpha: 1.0)
	}

	class func headerDarkGrayColor() -> UIColor {
		return UIColor(red: 204.0 / 255.0, green: 204.0 / 255.0, blue: 205.0 / 255.0, alpha: 1.0)
	}

	class func headerTitleGrayColor() -> UIColor {
		return UIColor(red: 112.0 / 255.0, green: 112.0 / 255.0, blue: 115.0 / 255.0, alpha: 1.0)
	}

	class func descriptionDarkGrayColor() -> UIColor {
		return UIColor(red: 56.0 / 255.0, green: 56.0 / 255.0, blue: 59.0 / 255.0, alpha: 1.0)
	}

	class func descriptionLightGrayColor() -> UIColor {
		return UIColor(red: 165.0 / 255.0, green: 165.0 / 255.0, blue: 167.0 / 255.0, alpha: 1.0)
	}
}
