//
//  UIFont+ZeplinAdditions.swift
//
//  Generated by Zeplin on 9/22/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
	class func screenTitleTextFont() -> UIFont? {
		return UIFont(name: "Avenir-Medium", size: 17.0)
	}

	class func buttonTextFont() -> UIFont? {
		return UIFont(name: "Avenir-Heavy", size: 14.0)
	}

	class func resultValueTextFont() -> UIFont? {
		return UIFont(name: "Avenir-Medium", size: 14.0)
	}

	class func descriptionTextFont() -> UIFont? {
		return UIFont(name: "Avenir-Book", size: 14.0)
	}

	class func resultLabelTextFont() -> UIFont? {
		return UIFont(name: "Avenir-Roman", size: 14.0)
	}

	class func headerTitleTextFont() -> UIFont? {
		return UIFont(name: "Avenir-Book", size: 11.0)
	}
}
